Факториал
js-tasks-ru/jsbasic-20230209_sp-dimon pull request #2
Opened 2023-02-19 10:17 UTC by SliceOfLiberty

2023-02-19 10:18 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-02-20 03:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-02-20 03:09 UTC, koalex requested changes
Исправить замечание в файле **package.json**

2023-02-20 03:09 UTC, koalex commented on package.json
> +    "karma-mocha-reporter": "^2.2.5",
Нужно в этом файле вернуть старый **karma-mocha-reporter**, должно быть
`"karma-mocha-reporter": "git+https://github.com/javascriptru/karma-mocha-reporter.git"`

2023-02-20 04:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-20 04:28 UTC, koalex requested changes
Нужно решить **1-2**

2023-02-21 08:14 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-02-21 09:44 UTC, koalex approved these changes

2023-02-21 09:44 UTC, merged